### ISSUE TITLE
Tassel To-Do

### ISSUE THREAD

**Issue by slin63** [slin63/django_NelsonDB#72]
- [x] Edit `CSV` script to output kinship matrix names instead of just `Her_K1`
- [x] Add `_rest` queries to hypotheses
- [x] Add all phenotypes to run-query
- [x] Write `gwas` query for NLB associations inc: CNV vs. SNP vs. indel
