### ISSUE TITLE
Todo:

### ISSUE THREAD

**Issue by slin63** [slin63/django_NelsonDB#87]
- [x] O1TS0018 `polli_type` to self
- [x] Add shelling info column
- [x] Fix caps sensitive `inbred` reading for `split_gen`
- [x] Add trailing zeroes for generated packet names (e.g. `01TS0004_001` instead of `01TS0004 - 1`
- [x] Remove male name from generated Seed ID's (e.g. `01TS0004_001` instead of `01TS0004 X 0003 - 1`)
- [x] BC (3 plots) 15 & 16 BC3 (gener.)
